# Baseline defaults the code actually reads
ewma_alpha: 0.1
min_warmup: 20

# Conformal settings
conformal_q: 0.90
conformal_maxlen: 2000

# Service/Pipeline limits
pending_cap: 4096
max_series: 1024

# Truth idempotency
truth_ttl_sec: 3600
truth_max_ids: 200000

# Regime threshold used by Pipeline/BOCPD in our code
regime_vol_threshold: 0.02

# Optional rate limiting (0 = disabled)
rate_limit_per_minute: 0

# Informational only (current code ignores these, but we keep them documented)
detector:
  threshold: 0.14      # heuristic cp sensitivity (our BOCPD maps 1/threshold)
  hazard: 0.004
  cooldown: 10
  mu0: 0.0
  kappa0: 1.0
  alpha0: 4.0
  beta0: 0.0008
  vol_threshold: 0.02

router:
  freeze_on_recent_cp: true
  freeze_ticks: 7
  switch_threshold: 0.1
  switch_penalty: 0.05
