detector:
  threshold: 0.2
  hazard: 0.0166666667
  cooldown: 3
  mu0: 0.0
  kappa0: 1.0
  alpha0: 4.0
  beta0: 0.0008
  vol_threshold: 0.02

router:
  dwell_min: 10
  switch_threshold: 0.1
  switch_penalty: 0.05
  freeze_on_recent_cp: true
  freeze_ticks: 5

arima:
  window: 500
  order: [1, 0, 0]
  seasonal_order: [0, 0, 0, 0]
  refit_every: 100

xgb:
  window: 2000
  retrain_every: 200
  min_train: 400
  n_estimators: 200
  max_depth: 5
  learning_rate: 0.05
