# Only override what you actually want different from default
regime_vol_threshold: 0.02

detector:
  threshold: 0.14
  hazard: 0.004
  cooldown: 10
  mu0: 0.0
  kappa0: 1.0
  alpha0: 4.0
  beta0: 0.0008
  vol_threshold: 0.02

router:
  freeze_on_recent_cp: true
  freeze_ticks: 7
  switch_threshold: 0.1
  switch_penalty: 0.05
