[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "regime-forecast"
version = "0.1.0"
description = "Regime detection + adaptive forecasting (MVP)"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
  # service
  "fastapi>=0.110",
  "uvicorn[standard]>=0.23",
  "pydantic>=2",
  "prometheus-client",
  "structlog",
  "pyyaml",

  # core / data
  "numpy>=1.26",
  "pandas>=2.0",
  "pyarrow>=14",         # parquet in data.replay
  "scipy>=1.11",         # statsmodels runtime

  # models (optional at runtime but imported; we provide them so service isn't crippled)
  "statsmodels>=0.14",
  "scikit-learn>=1.3",
  "xgboost>=2.0",

  # data utilities
  "yfinance>=0.2",
]

[project.optional-dependencies]
dev = [
  "pytest",
  "httpx",
  "ruff",
  "mypy",
  "pre-commit",
]

[tool.ruff]
line-length = 100
target-version = "py311"
select = ["E","F","I","UP","B","SIM","PT","N","C90"]

[tool.mypy]
python_version = "3.11"
warn_unused_ignores = true
show_error_codes = true
ignore_missing_imports = true

[tool.pytest.ini_options]
addopts = "-q"
testpaths = ["tests"]

[tool.setuptools]
package-dir = {"" = "."}

[tool.setuptools.packages.find]
include = ["core*", "models*", "service*"]
exclude = ["tests*", "scripts*", "data*", "config*", "backtest*"]
