[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "regime-forecast"
version = "0.1.0"
description = "Regime detection + adaptive forecasting (MVP)"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
  "fastapi",
  "uvicorn[standard]",
  "pydantic>=2",
  "prometheus-client",
  "structlog"
]
[project.optional-dependencies]
dev = ["pytest","httpx","ruff","mypy","pre-commit"]
[tool.ruff]
line-length = 100
target-version = "py311"
select = ["E","F","I","UP","B","SIM","PT","N","C90"]

[tool.mypy]
python_version = "3.11"
warn_unused_ignores = true
show_error_codes = true
ignore_missing_imports = true

[tool.pytest.ini_options]
addopts = "-q"
testpaths = ["tests"]
