groups:
  - name: regime-forecast
    rules:
      - alert: PredictTrafficMissing
        expr: absent(rate(requests_total{endpoint="predict"}[10m]))
        for: 10m
        labels:
          severity: warning
        annotations:
          description: No /predict traffic for 10m
          summary: predict traffic absent

      - alert: HighServiceLatencyP95
        expr: histogram_quantile(0.95, sum(rate(latency_ms_bucket{stage="service_ms"}[5m])) by (le)) > 200
        for: 10m
        labels:
          severity: warning
        annotations:
          description: p95 service latency > 200ms for 10m
          summary: high latency

      - alert: RouterOrModelLatencyP95High
        expr: histogram_quantile(0.95, sum(rate(latency_ms_bucket{stage=~"router_ms|model_ms|detector_ms|features_ms|conformal_ms"}[5m])) by (stage,le)) > 150
        for: 10m
        labels:
          severity: info
        annotations:
          description: p95 stage latency > 150ms
          summary: stage latency high
