name: ci

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11', '3.12']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install deps
        run: |
          python -m pip install -U pip wheel
          # core dev tools
          pip install ruff mypy pytest types-PyYAML
          # libs needed for sim + backtest CLI
          pip install numpy pandas
          # install package (if needed)
          pip install -e .
      - name: Ruff
        run: ruff check .
      - name: Mypy
        run: mypy .
      - name: Pytest
        run: pytest -q
      - name: Backtest (sim)
        run: |
          python data/sim_cp.py --out data/sim_cp.csv
          python backtest/cli.py --data data/sim_cp.csv --cp_tol 10 --profile sim
